
// ** Home


// ** Auth
export const resetAuthActionTypes = {
    RESET_ACTION: 'RESET_AUTH_ACTION',
}

export const signInActionTypes = {
    REQUEST_ACTION: 'SIGNIN_REQUEST_ACTION',
    SUCCESS_ACTION: 'SIGNIN_SUCCESS_ACTION',
    FAILED_ACTION: 'SIGNIN_FAILED_ACTION',
    STORE_USERID_ACTION: 'STORE_USERID_ACTION',
    STORE_TOKEN_ACTION: 'STORE_TOKEN_ACTION',
    SESSION_EXPIRED_ACTION: 'SESSION_EXPIRED_ACTION',
}
